apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: payments-ms
        name: payments-ms
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVER
            value: "nats://nats"
          - name: STRIPE_SUCCESS_URL
            value: "htpp://localhost:3000/payments/success"
          - name: STRIPE_CANCEL_URL
            value: "htpp://localhost:3000/payments/cancel"
          - name: STRIPE_SECRET
            valueFrom:
              secretKetRef:
                name: payments-secrets
                key: stripe_secret
          - name: STRIPE_ENDPOINT_SECRET
            valueFrom:
              secretKetRef:
                name: payments-secrets
                key: stripe_endpoint_secret          
          - name: JWT_SECRET
            value: ""
        resources: {}
status: {}
